const FIREBASE_VERSION = "12.9.0";
const VERIFICATION_RESEND_COOLDOWN_MS = 45 * 1000;
const config = window.HOC_CUNG_BE_FIREBASE_CONFIG;
const hasFirebaseConfig = Boolean(config && config.apiKey && config.authDomain && config.projectId && config.appId && !String(config.apiKey).startsWith("PASTE_"));
let firebase = null, firestore = null, auth = null, db = null, currentUser = null;
let phoneVerificationId = null, recaptchaVerifier = null, resendAvailableAt = 0, resendCountdownTimer = null;
const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];

function accountMessage(code) {
  return ({
    "auth/invalid-email": "Email không hợp lệ.",
    "auth/email-already-in-use": "Email này đã được đăng ký.",
    "auth/invalid-credential": "Email hoặc mật khẩu không đúng.",
    "auth/wrong-password": "Email hoặc mật khẩu không đúng.",
    "auth/user-not-found": "Email hoặc mật khẩu không đúng.",
    "auth/weak-password": "Mật khẩu mới chưa đủ mạnh.",
    "auth/too-many-requests": "Bạn đã thử quá nhiều lần. Vui lòng thử lại sau.",
    "auth/network-request-failed": "Không thể kết nối mạng.",
    "auth/requires-recent-login": "Vui lòng nhập mật khẩu hiện tại để xác thực lại.",
    "auth/credential-already-in-use": "Số điện thoại này đã liên kết với một tài khoản khác.",
    "auth/provider-already-linked": "Số điện thoại này đã được liên kết với tài khoản này.",
    "auth/invalid-verification-code": "Mã OTP chưa đúng. Vui lòng kiểm tra và thử lại.",
    "auth/code-expired": "Mã OTP đã hết hạn. Vui lòng gửi lại mã.",
    "auth/captcha-check-failed": "Xác minh reCAPTCHA chưa thành công. Vui lòng thử lại.",
    "auth/invalid-phone-number": "Số điện thoại chưa đúng định dạng.",
    "auth/missing-phone-number": "Vui lòng nhập số điện thoại.",
    "auth/quota-exceeded": "Không thể gửi mã lúc này. Vui lòng thử lại sau.",
    "auth/operation-not-allowed": "Phương thức đăng nhập này chưa được bật trong Firebase Console.",
  })[code] || "Không thể hoàn tất yêu cầu. Vui lòng thử lại.";
}
function changePasswordMessage(code) { return code === "auth/wrong-password" || code === "auth/invalid-credential" ? "Mật khẩu hiện tại chưa đúng." : accountMessage(code); }
function normalizeVietnamPhone(value) { const digits = String(value || "").trim().replace(/[\s().-]/g, ""); if (/^\+84\d{9,10}$/.test(digits)) return digits; if (/^84\d{9,10}$/.test(digits)) return `+${digits}`; if (/^0\d{9,10}$/.test(digits)) return `+84${digits.slice(1)}`; return null; }
function maskPhone(phone) { if (!phone) return "Chưa liên kết"; const local = phone.replace(/^\+84/, "0"); return local.length > 4 ? `${local.slice(0, 2)}******${local.slice(-2)}` : "Đã liên kết"; }
function isValidEmail(email) { return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(email).trim()); }
function passwordError(password) { return String(password).length >= 6 ? "" : "Mật khẩu mới cần có ít nhất 6 ký tự."; }
function passwordChangeValidation(currentPassword, nextPassword, confirmPassword) { if (!currentPassword || !nextPassword || !confirmPassword) return "Vui lòng nhập đầy đủ ba trường mật khẩu."; return passwordError(nextPassword) || (nextPassword === confirmPassword ? "" : "Hai mật khẩu mới chưa giống nhau."); }
function setStatus(panel, text = "", type = "") { const output = $("[data-account-status]", panel); if (!output) return; output.textContent = text; output.className = `account-status ${type}`; }
function setBusy(button, busy, label) { if (!button) return; if (label) button.dataset.label = label; if (!button.dataset.label) button.dataset.label = button.textContent; button.disabled = busy; button.textContent = busy ? "Đang xử lý…" : button.dataset.label; }
function formatFirebaseTime(value) { return value && !Number.isNaN(new Date(value).getTime()) ? new Date(value).toLocaleString("vi-VN", { dateStyle: "short", timeStyle: "short" }) : "Chưa có thông tin"; }
function showAccountScreen(name) { $$(".screen").forEach((screen) => { screen.hidden = screen.id !== `account-${name}-screen`; }); window.scrollTo({ top: 0, behavior: "smooth" }); $("input, button", $(`#account-${name}-screen`))?.focus({ preventScroll: true }); }
function showHome() { $$(".screen").forEach((screen) => { screen.hidden = screen.id !== "home-screen"; }); window.scrollTo({ top: 0, behavior: "smooth" }); }
function authUnavailableMessage(online, authReady) { if (!online) return "Cần kết nối Internet để thực hiện thao tác này."; return authReady ? "" : "Firebase Authentication chưa được cấu hình. Phần học của bé vẫn hoạt động bình thường."; }
function accountUnavailable(panel) { const message = authUnavailableMessage(navigator.onLine, Boolean(auth)); if (!message) return false; setStatus(panel, message, "is-error"); return true; }

function accountMarkup() {
  const entry = document.createElement("section");
  entry.className = "parent-account-entry"; entry.id = "parent-account-entry";
  entry.innerHTML = `<div><p class="eyebrow">Dành cho người lớn</p><h2>👤 Tài khoản phụ huynh</h2><p id="parent-account-summary">Đăng nhập để đồng bộ tiến độ giữa các thiết bị. Dữ liệu local hiện có luôn được giữ lại.</p></div><div class="parent-account-entry__actions" id="parent-account-actions"></div>`;
  $("#home-screen").append(entry);
  document.querySelector("main").insertAdjacentHTML("beforeend", `
  <section class="screen account-screen" id="account-register-screen" hidden><div class="account-panel"><button class="back-button" data-account-home>← Trang chủ</button><p class="eyebrow">Tài khoản phụ huynh</p><h1>Đăng ký tài khoản phụ huynh</h1><p class="account-intro">Tài khoản dành cho phụ huynh. Bé không cần cung cấp email hoặc số điện thoại.</p><form id="register-form" novalidate><label>Họ và tên phụ huynh<input name="name" autocomplete="name" required maxlength="100" /></label><label>Email<input name="email" type="email" inputmode="email" autocomplete="email" required /></label><label>Mật khẩu<span class="password-field"><input name="password" type="password" autocomplete="new-password" required minlength="6" /><button type="button" class="password-toggle" data-password-toggle>Hiện</button></span></label><label>Nhập lại mật khẩu<span class="password-field"><input name="confirmPassword" type="password" autocomplete="new-password" required minlength="6" /><button type="button" class="password-toggle" data-password-toggle>Hiện</button></span></label><label class="account-check"><input name="terms" type="checkbox" required /> Tôi đồng ý với <button type="button" class="inline-link" data-account-go="privacy">Điều khoản sử dụng và Chính sách quyền riêng tư</button>.</label><p class="account-status" data-account-status role="status" aria-live="polite"></p><button class="primary-button" type="submit">Đăng ký</button></form><p class="account-switch">Đã có tài khoản? <button type="button" class="inline-link" data-account-go="login">Đăng nhập</button></p></div></section>
  <section class="screen account-screen" id="account-login-screen" hidden><div class="account-panel"><button class="back-button" data-account-home>← Trang chủ</button><p class="eyebrow">Tài khoản phụ huynh</p><h1>Đăng nhập</h1><form id="login-form" novalidate><label>Email<input name="email" type="email" inputmode="email" autocomplete="email" required /></label><label>Mật khẩu<span class="password-field"><input name="password" type="password" autocomplete="current-password" required /><button type="button" class="password-toggle" data-password-toggle>Hiện</button></span></label><p class="account-status" data-account-status role="status" aria-live="polite"></p><button class="primary-button" type="submit">Đăng nhập</button></form><p class="account-switch"><button type="button" class="inline-link" data-account-go="forgot">Quên mật khẩu?</button> · Chưa có tài khoản? <button type="button" class="inline-link" data-account-go="register">Đăng ký</button></p></div></section>
  <section class="screen account-screen" id="account-forgot-screen" hidden><div class="account-panel"><button class="back-button" data-account-home>← Trang chủ</button><p class="eyebrow">Tài khoản phụ huynh</p><h1>Quên mật khẩu</h1><p class="account-intro">Nhập email của phụ huynh để nhận hướng dẫn đặt lại mật khẩu.</p><form id="forgot-form" novalidate><label>Email<input name="email" type="email" inputmode="email" autocomplete="email" required /></label><p class="account-status" data-account-status role="status" aria-live="polite"></p><button class="primary-button" type="submit">Gửi hướng dẫn đặt lại</button></form><p class="account-switch"><button type="button" class="inline-link" data-account-go="login">Quay lại đăng nhập</button></p></div></section>
  <section class="screen account-screen" id="account-me-screen" hidden><div class="account-panel"><button class="back-button" data-account-home>← Trang chủ</button><p class="eyebrow">Tài khoản phụ huynh</p><h1>Tài khoản của tôi</h1><div class="account-details"><div><span>Tên phụ huynh</span><strong id="account-name">—</strong></div><div><span>Email</span><strong id="account-email">—</strong></div><div><span>Trạng thái email</span><strong id="account-verified">—</strong></div><div><span>Số điện thoại</span><strong id="account-phone">—</strong></div><div><span>Lần đăng nhập hiện tại</span><strong id="account-last-sign-in">—</strong></div></div><p class="account-security-note" id="account-verification-note">Khuyến nghị xác minh email để bảo vệ tài khoản. Việc học và đồng bộ tiến độ không bị chặn.</p><div class="account-actions"><button class="secondary-button" id="resend-verification" type="button">Gửi lại email xác minh</button><button class="secondary-button" id="refresh-verification" type="button">Kiểm tra lại trạng thái xác minh</button><button class="secondary-button" id="open-phone-link" type="button">Liên kết số điện thoại</button><button class="secondary-button" id="open-password-change" type="button">Đổi mật khẩu</button><button class="danger-button" id="account-signout" type="button">Đăng xuất</button></div><section class="account-subpanel" id="phone-link-panel" hidden><h2>Liên kết số điện thoại</h2><p>Chỉ dùng test phone number trước khi tự quyết định bật SMS production.</p><label>Số điện thoại<input id="phone-number" inputmode="tel" autocomplete="tel" placeholder="0912345678" /></label><button class="secondary-button" id="send-phone-code" type="button">Gửi mã OTP</button><div id="phone-code-area" hidden><label>Mã OTP<input id="phone-code" inputmode="numeric" autocomplete="one-time-code" maxlength="6" /></label><button class="secondary-button" id="confirm-phone-code" type="button">Xác minh và liên kết</button></div><div id="phone-recaptcha"></div></section><section class="account-subpanel" id="password-change-panel" hidden><h2>Đổi mật khẩu</h2><label>Mật khẩu hiện tại<span class="password-field"><input id="current-password" type="password" autocomplete="current-password" /><button type="button" class="password-toggle" data-password-toggle>Hiện</button></span></label><label>Mật khẩu mới<span class="password-field"><input id="new-password" type="password" autocomplete="new-password" minlength="6" /><button type="button" class="password-toggle" data-password-toggle>Hiện</button></span></label><label>Nhập lại mật khẩu mới<span class="password-field"><input id="confirm-new-password" type="password" autocomplete="new-password" minlength="6" /><button type="button" class="password-toggle" data-password-toggle>Hiện</button></span></label><button class="primary-button" id="change-password" type="button">Lưu mật khẩu mới</button></section><p class="account-status" data-account-status role="status" aria-live="polite"></p></div></section>
  <section class="screen account-screen" id="account-privacy-screen" hidden><div class="account-panel"><button class="back-button" data-account-home>← Trang chủ</button><p class="eyebrow">Thông tin tài khoản</p><h1>Chính sách quyền riêng tư</h1><p>Đây là nội dung placeholder cần chủ website rà soát trước khi công bố. Ứng dụng không lưu mật khẩu, OTP, mã xác minh email hoặc mã đặt lại mật khẩu vào localStorage hay Firestore.</p><button type="button" class="inline-link" data-account-go="register">Quay lại đăng ký</button></div></section>`);
}

function bindAccountLinks() { $$('[data-account-go]').forEach((button) => { button.onclick = () => showAccountScreen(button.dataset.accountGo); }); }
function publishAuthState(user) { window.dispatchEvent(new CustomEvent("hoc-cung-be:auth-state", { detail: { user: user || null } })); }
function verificationStatusText(user) { return user?.emailVerified ? "✓ Email đã xác minh" : "⚠ Email chưa xác minh"; }
function resendSecondsRemaining(now = Date.now()) { return Math.max(0, Math.ceil((resendAvailableAt - now) / 1000)); }
function updateVerificationButtons() { const resend = $("#resend-verification"), refresh = $("#refresh-verification"); if (!resend || !refresh) return; const seconds = resendSecondsRemaining(), verified = Boolean(currentUser?.emailVerified); resend.disabled = !currentUser || verified || seconds > 0; resend.textContent = seconds ? `Gửi lại sau ${seconds}s` : "Gửi lại email xác minh"; refresh.disabled = !currentUser; }
function startResendCooldown(now = Date.now()) { resendAvailableAt = now + VERIFICATION_RESEND_COOLDOWN_MS; clearInterval(resendCountdownTimer); updateVerificationButtons(); resendCountdownTimer = setInterval(() => { updateVerificationButtons(); if (!resendSecondsRemaining()) { clearInterval(resendCountdownTimer); resendCountdownTimer = null; } }, 1000); }
function renderAuthUi(user = currentUser) {
  const actions = $("#parent-account-actions"), summary = $("#parent-account-summary"); if (!actions) return;
  if (user) {
    const name = user.displayName || user.email || "Phụ huynh";
    summary.textContent = `${name} · Đã đăng nhập. Tiến độ vẫn lưu local trước và đồng bộ Cloud Firestore khi có mạng.${user.emailVerified ? "" : " Khuyến nghị xác minh email để bảo vệ tài khoản."}`;
    actions.innerHTML = `<button class="parent-entry__button" type="button" data-account-go="me">Tài khoản của tôi</button><button class="parent-entry__button" type="button" data-cloud-sync-button>☁️ Đồng bộ</button><button class="parent-entry__button" type="button" id="quick-signout">Đăng xuất</button>`;
    $("#quick-signout").onclick = signOutParent; $("#account-name").textContent = user.displayName || "Chưa cập nhật"; $("#account-email").textContent = user.email || "—"; $("#account-verified").textContent = verificationStatusText(user); $("#account-verified").dataset.verified = String(Boolean(user.emailVerified)); $("#account-phone").textContent = maskPhone(user.phoneNumber); $("#account-last-sign-in").textContent = formatFirebaseTime(user.metadata?.lastSignInTime); $("#account-verification-note").hidden = Boolean(user.emailVerified);
  } else { summary.textContent = "Đăng nhập để mở toàn bộ bài học và đồng bộ tiến độ giữa các thiết bị. Tiến độ local hiện có luôn được giữ lại."; actions.innerHTML = `<button class="parent-entry__button" type="button" data-account-go="login">Đăng nhập</button><button class="parent-entry__button parent-entry__button--primary" type="button" data-account-go="register">Đăng ký</button>`; }
  bindAccountLinks(); updateVerificationButtons(); window.HocCungBeCloudSync?.installUi();
}

function profilePayload(user) { return { uid: user.uid, displayName: user.displayName || null, email: user.email || null, emailVerified: Boolean(user.emailVerified), createdAt: user.metadata?.creationTime || null }; }
async function updateFirestoreProfile(user, sdk = firestore, database = db) { if (!user || !sdk || !database) return false; await sdk.setDoc(sdk.doc(database, "users", user.uid), { ...profilePayload(user), updatedAt: sdk.serverTimestamp() }, { merge: true }); return true; }
async function sendVerificationEmail(user, sdk = firebase) { await sdk.sendEmailVerification(user); return true; }
async function sendResetEmail(email, sdk = firebase, authInstance = auth) { await sdk.sendPasswordResetEmail(authInstance, email); return true; }
async function changePasswordWithReauth(user, currentPassword, nextPassword, sdk = firebase) { const credential = sdk.EmailAuthProvider.credential(user.email, currentPassword); await sdk.reauthenticateWithCredential(user, credential); await sdk.updatePassword(user, nextPassword); return true; }
async function reloadVerifiedUser(user, sdk = firebase, authInstance = auth) { await sdk.reload(user); return authInstance?.currentUser || user; }

async function loadFirebase() {
  if (!hasFirebaseConfig) return;
  try {
    const appSdk = await import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-app.js`); firebase = await import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-auth.js`); firestore = await import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-firestore.js`);
    const app = appSdk.initializeApp(config); auth = firebase.getAuth(app); db = firestore.getFirestore(app); await firebase.setPersistence(auth, firebase.browserLocalPersistence);
    firebase.onAuthStateChanged(auth, async (user) => { currentUser = user; renderAuthUi(user); publishAuthState(user); if (user) { try { await updateFirestoreProfile(user); } catch (error) { console.warn("Không thể cập nhật profile Firestore.", error); } await window.HocCungBeCloudSync?.configure({ firestore, db, user }); } else window.HocCungBeCloudSync?.disconnect(); });
  } catch (error) { console.warn("Không thể khởi tạo Firebase Authentication hoặc Cloud Firestore.", error); }
}

async function registerParent(event) {
  event.preventDefault(); const form = event.currentTarget, panel = form.closest(".account-panel"), name = form.name.value.trim(), email = form.email.value.trim(), password = form.password.value, confirm = form.confirmPassword.value;
  const validation = !name ? "Vui lòng nhập họ và tên phụ huynh." : !isValidEmail(email) ? "Email không hợp lệ." : passwordError(password) || (password !== confirm ? "Hai mật khẩu chưa giống nhau." : (!form.terms.checked ? "Vui lòng đồng ý với Điều khoản sử dụng và Chính sách quyền riêng tư." : ""));
  if (validation) { setStatus(panel, validation, "is-error"); return; } if (accountUnavailable(panel)) return; const submit = $("button[type=submit]", form); setBusy(submit, true, "Đăng ký");
  try { const result = await firebase.createUserWithEmailAndPassword(auth, email, password); await firebase.updateProfile(result.user, { displayName: name }); currentUser = result.user; await sendVerificationEmail(result.user); try { await updateFirestoreProfile(result.user); } catch (profileError) { console.warn("Không thể cập nhật profile Firestore sau đăng ký.", profileError); } startResendCooldown(); renderAuthUi(result.user); setStatus(panel, `Đăng ký thành công.\nChúng tôi đã gửi email xác minh tới ${email}.\nVui lòng kiểm tra hộp thư.`, "is-success"); form.reset(); } catch (error) { setStatus(panel, accountMessage(error.code), "is-error"); } finally { setBusy(submit, false); }
}
async function loginParent(event) { event.preventDefault(); const form = event.currentTarget, panel = form.closest(".account-panel"), email = form.email.value.trim(), password = form.password.value; if (!isValidEmail(email) || !password) { setStatus(panel, !isValidEmail(email) ? "Email không hợp lệ." : "Vui lòng nhập mật khẩu.", "is-error"); return; } if (accountUnavailable(panel)) return; const submit = $("button[type=submit]", form); setBusy(submit, true, "Đăng nhập"); try { await firebase.signInWithEmailAndPassword(auth, email, password); form.reset(); showHome(); } catch (error) { setStatus(panel, accountMessage(error.code), "is-error"); } finally { setBusy(submit, false); } }
async function forgotPassword(event) { event.preventDefault(); const form = event.currentTarget, panel = form.closest(".account-panel"), email = form.email.value.trim(); if (!isValidEmail(email)) { setStatus(panel, "Email không hợp lệ.", "is-error"); return; } if (accountUnavailable(panel)) return; const submit = $("button[type=submit]", form); setBusy(submit, true, "Gửi hướng dẫn đặt lại"); try { await sendResetEmail(email); } catch (_) {} finally { setStatus(panel, "Nếu email này đã được đăng ký, hướng dẫn đặt lại mật khẩu sẽ được gửi tới hộp thư.", "is-success"); setBusy(submit, false); } }
async function signOutParent() { if (!auth) return; try { await firebase.signOut(auth); showHome(); } catch (error) { setStatus($("#account-me-screen"), accountMessage(error.code), "is-error"); } }
async function resendVerification() { const panel = $("#account-me-screen"); if (accountUnavailable(panel) || !currentUser || currentUser.emailVerified) return; if (resendSecondsRemaining()) return updateVerificationButtons(); const button = $("#resend-verification"); setBusy(button, true, "Gửi lại email xác minh"); try { await sendVerificationEmail(currentUser); startResendCooldown(); setStatus(panel, "Đã gửi lại email xác minh.", "is-success"); } catch (error) { setStatus(panel, accountMessage(error.code), "is-error"); } finally { setBusy(button, false); updateVerificationButtons(); } }
async function reloadVerificationStatus() { const panel = $("#account-me-screen"); if (accountUnavailable(panel) || !currentUser) return; const button = $("#refresh-verification"); setBusy(button, true, "Kiểm tra lại trạng thái xác minh"); try { currentUser = await reloadVerifiedUser(currentUser); renderAuthUi(currentUser); publishAuthState(currentUser); let profileUpdated = true; try { await updateFirestoreProfile(currentUser); } catch (profileError) { profileUpdated = false; console.warn("Không thể cập nhật trạng thái xác minh lên Firestore.", profileError); } const verifiedMessage = profileUpdated ? "Email đã được xác minh." : "Email đã được xác minh. Chưa thể cập nhật profile Firestore; vui lòng thử lại khi có mạng ổn định."; setStatus(panel, currentUser.emailVerified ? verifiedMessage : "Email chưa được xác minh. Vui lòng kiểm tra hộp thư và thử lại.", currentUser.emailVerified ? "is-success" : "is-error"); } catch (error) { setStatus(panel, accountMessage(error.code), "is-error"); } finally { setBusy(button, false); updateVerificationButtons(); } }

async function sendPhoneCode() { const panel = $("#account-me-screen"), number = normalizeVietnamPhone($("#phone-number").value); if (!number) { setStatus(panel, "Nhập số Việt Nam dạng 0912345678 hoặc +84912345678.", "is-error"); return; } if (accountUnavailable(panel) || !currentUser) return; const button = $("#send-phone-code"); setBusy(button, true, "Gửi mã OTP"); try { recaptchaVerifier?.clear(); recaptchaVerifier = new firebase.RecaptchaVerifier(auth, "phone-recaptcha", { size: "invisible", "expired-callback": () => setStatus(panel, "Xác minh reCAPTCHA đã hết hạn. Vui lòng gửi lại mã.", "is-error") }); await recaptchaVerifier.render(); phoneVerificationId = await new firebase.PhoneAuthProvider(auth).verifyPhoneNumber(number, recaptchaVerifier); $("#phone-code-area").hidden = false; $("#phone-code").focus(); setStatus(panel, "Mã OTP đã được gửi. Với test phone number, dùng mã đã đặt trong Firebase Console.", "is-success"); } catch (error) { recaptchaVerifier?.clear(); recaptchaVerifier = null; setStatus(panel, accountMessage(error.code), "is-error"); } finally { setBusy(button, false); } }
async function confirmPhoneCode() { const panel = $("#account-me-screen"), code = $("#phone-code").value.trim(); if (!phoneVerificationId || !/^\d{6}$/.test(code)) { setStatus(panel, "Vui lòng nhập mã OTP gồm 6 chữ số.", "is-error"); return; } if (accountUnavailable(panel) || !currentUser) return; const button = $("#confirm-phone-code"); setBusy(button, true, "Xác minh và liên kết"); try { await firebase.linkWithCredential(currentUser, firebase.PhoneAuthProvider.credential(phoneVerificationId, code)); phoneVerificationId = null; $("#phone-code-area").hidden = true; $("#phone-number").value = ""; $("#phone-code").value = ""; renderAuthUi(currentUser); await updateFirestoreProfile(currentUser); setStatus(panel, "Đã liên kết số điện thoại với tài khoản phụ huynh này.", "is-success"); } catch (error) { setStatus(panel, accountMessage(error.code), "is-error"); } finally { setBusy(button, false); } }
async function changePassword() { const panel = $("#account-me-screen"), currentPassword = $("#current-password").value, nextPassword = $("#new-password").value, confirmPassword = $("#confirm-new-password").value, validation = passwordChangeValidation(currentPassword, nextPassword, confirmPassword); if (validation) { setStatus(panel, validation, "is-error"); return; } if (accountUnavailable(panel) || !currentUser?.email) return; const button = $("#change-password"); setBusy(button, true, "Lưu mật khẩu mới"); try { await changePasswordWithReauth(currentUser, currentPassword, nextPassword); $("#current-password").value = ""; $("#new-password").value = ""; $("#confirm-new-password").value = ""; $("#password-change-panel").hidden = true; setStatus(panel, "Đã đổi mật khẩu thành công.", "is-success"); } catch (error) { setStatus(panel, changePasswordMessage(error.code), "is-error"); } finally { setBusy(button, false); } }

async function addSelfTests() {
  const progressBefore = localStorage.getItem("hoc-cung-be:math-grade-1-progress"), pinBefore = localStorage.getItem("hoc-cung-be:parent-pin"), storageBefore = JSON.stringify(localStorage), tests = [], test = (name, passed) => tests.push({ name, passed: Boolean(passed) });
  const mockUser = { uid: "mock-parent", displayName: "Phụ huynh thử", email: "parent@example.com", emailVerified: false, phoneNumber: "+84912345678", metadata: { creationTime: "2026-01-01T00:00:00.000Z", lastSignInTime: "2026-10-02T12:00:00.000Z" } };
  let verificationCalls = 0; await sendVerificationEmail(mockUser, { sendEmailVerification: async () => { verificationCalls += 1; } }); test("A: Register success triggers verification flow", verificationCalls === 1);
  currentUser = mockUser; renderAuthUi(mockUser); test("B: Verified=false UI đúng", $("#account-verified").textContent === "⚠ Email chưa xác minh"); test("C: Resend verification helper đúng", typeof resendVerification === "function" && VERIFICATION_RESEND_COOLDOWN_MS >= 30000);
  const verifiedUser = { ...mockUser, emailVerified: true }; const reloadedUser = await reloadVerifiedUser(mockUser, { reload: async (user) => { user.emailVerified = true; } }, { currentUser: verifiedUser }); currentUser = reloadedUser; renderAuthUi(reloadedUser); test("D: Reload verified=true cập nhật UI", reloadedUser.emailVerified && $("#account-verified").textContent === "✓ Email đã xác minh");
  test("E: Forgot password validation", isValidEmail("parent@example.com") && !isValidEmail("bad")); let resetEmail = ""; await sendResetEmail(mockUser.email, { sendPasswordResetEmail: async (_auth, email) => { resetEmail = email; } }, {}); test("F: Reset email helper", resetEmail === mockUser.email);
  test("G: Change password mismatch", passwordChangeValidation("oldpass", "newpass", "different") === "Hai mật khẩu mới chưa giống nhau."); const steps = []; await changePasswordWithReauth(mockUser, "oldpass", "newpass", { EmailAuthProvider: { credential: (email) => ({ email }) }, reauthenticateWithCredential: async () => steps.push("reauth"), updatePassword: async () => steps.push("update") }); test("H: Change password reauth flow", steps.join(",") === "reauth,update"); test("I: Wrong current password mapping", changePasswordMessage("auth/wrong-password") === "Mật khẩu hiện tại chưa đúng.");
  test("J: Password không lưu localStorage", JSON.stringify(localStorage) === storageBefore); let savedProfile = null; await updateFirestoreProfile(verifiedUser, { doc: () => "users/mock-parent", serverTimestamp: () => "server-time", setDoc: async (_ref, data, options) => { savedProfile = { data, options }; } }, {}); test("K: Firestore profile emailVerified update", savedProfile?.data.emailVerified === true && savedProfile?.options.merge === true);
  test("L: Cloud progress không bị ảnh hưởng", localStorage.getItem("hoc-cung-be:math-grade-1-progress") === progressBefore && typeof window.HocCungBeCloudSync?.syncNow === "function"); test("M: Parent PIN không bị ảnh hưởng", localStorage.getItem("hoc-cung-be:parent-pin") === pinBefore); test("N: Offline auth operations handled", authUnavailableMessage(false, true) === "Cần kết nối Internet để thực hiện thao tác này." && accountMessage("auth/network-request-failed") === "Không thể kết nối mạng."); test("O: PWA vẫn hoạt động", "serviceWorker" in navigator && document.querySelector('link[rel="manifest"]')?.getAttribute("href") === "manifest.webmanifest");
  currentUser = null; renderAuthUi(null); return tests;
}

function setup() {
  accountMarkup(); window.addEventListener("hoc-cung-be:open-auth", (event) => showAccountScreen(event.detail?.screen === "register" ? "register" : "login"));
  document.addEventListener("click", (event) => { const toggle = event.target.closest("[data-password-toggle]"); if (toggle) { const input = $("input", toggle.parentElement); input.type = input.type === "password" ? "text" : "password"; toggle.textContent = input.type === "password" ? "Hiện" : "Ẩn"; toggle.setAttribute("aria-label", input.type === "password" ? "Hiện mật khẩu" : "Ẩn mật khẩu"); } if (event.target.closest("[data-account-home]")) showHome(); if (event.target.closest("[data-go]")) $$(".account-screen").forEach((screen) => { screen.hidden = true; }); });
  $("#register-form").addEventListener("submit", registerParent); $("#login-form").addEventListener("submit", loginParent); $("#forgot-form").addEventListener("submit", forgotPassword); $("#resend-verification").onclick = resendVerification; $("#refresh-verification").onclick = reloadVerificationStatus; $("#open-phone-link").onclick = () => { $("#phone-link-panel").hidden = !$("#phone-link-panel").hidden; }; $("#open-password-change").onclick = () => { $("#password-change-panel").hidden = !$("#password-change-panel").hidden; }; $("#account-signout").onclick = signOutParent; $("#send-phone-code").onclick = sendPhoneCode; $("#confirm-phone-code").onclick = confirmPhoneCode; $("#change-password").onclick = changePassword;
  renderAuthUi(); window.__hocCungBeParentAuthTests = addSelfTests(); loadFirebase();
}
setup();